[Dropbox] Documentation for Advanced sync rules
elastic/connectors-python pull request #1322
Opened 2023-07-21 11:24 UTC by moxarth-elastic

## Closes https://github.com/elastic/connectors-python/issues/949

This PR contains the documentation of Dropbox connector advanced sync rules.

## Checklists

#### Pre-Review Checklist
- [x] this PR has a meaningful title
- [x] this PR links to all relevant github issues that it fixes or partially addresses
- [x] if there is no GH issue, please create it. Each PR should have a link to an issue
- [x] this PR has a thorough description
- [x] Covered the changes with automated tests
- [x] Tested the changes locally
- [x] Added a label for each target release version (example: `v7.13.2`, `v7.14.0`, `v8.0.0`)

2023-07-24 16:25 UTC, seanstory approved these changes

2023-07-24 16:34 UTC, leemthompo commented on docs/sync-rules/DROPBOX.md
> +### Setting up the Jira connector
```suggestion
### Setting up the Dropbox connector
```

2023-07-24 16:35 UTC, leemthompo commented on docs/reference/dropbox.md
> +Advanced Sync Rules are now available in elastic 8.10 version.
```suggestion
Advanced Sync Rules are available as of Elastic version 8.10.
```

2023-07-25 11:35 UTC, leemthompo commented on docs/reference/dropbox.md
> +- Users can add [Dropbox queries](https://www.dropbox.com/developers/documentation/http/documentation#files-search) for syncing the source.
```suggestion
- Users can add [Dropbox query](https://www.dropbox.com/developers/documentation/http/documentation#files-search) results to their syncs .
```

Correct rephrasing?

2023-07-25 11:40 UTC, leemthompo requested changes

2023-07-25 11:40 UTC, leemthompo commented on docs/reference/dropbox.md
> +    - Check the search response from [Dropbox API Explorer](https://dropbox.github.io/dropbox-api-v2-explorer/#files_search_v2).
```suggestion
    - Test search responses using the [Dropbox API Explorer](https://dropbox.github.io/dropbox-api-v2-explorer/#files_search_v2).
```

2023-07-25 11:40 UTC, leemthompo commented on docs/reference/dropbox.md
> +- All the data returned by queries will be indexed.
```suggestion
- All data returned by queries will be indexed.
```

2023-07-25 11:40 UTC, leemthompo commented on docs/reference/dropbox.md
> +**Note:** "path" configuration field will be overridden by the advanced rules.
```suggestion
**Note:** The "path" configuration field will be overridden by the advanced rules.
```

2023-07-25 11:40 UTC, leemthompo commented on docs/sync-rules/DROPBOX.md
> +#### Two rules for indexing content based on the query only
```suggestion
#### Two rules for indexing content based on queries only
```

2023-07-25 11:40 UTC, leemthompo commented on docs/sync-rules/DROPBOX.md
> +#### One query for indexing data based on the file_extensions
```suggestion
#### Single query for indexing data based on file extensions
```

2023-07-25 11:40 UTC, leemthompo commented on docs/sync-rules/DROPBOX.md
> +#### One query for indexing data based on file_categories
```suggestion
#### Single query for indexing data based on file categories
```

2023-07-25 11:40 UTC, leemthompo commented on docs/sync-rules/DROPBOX.md
> +- In case, both `file_extensions` and `file_categories` are provided, priority is given to `file_categories`.
```suggestion
- If both `file_extensions` and `file_categories` are provided, priority is given to `file_categories`.
```

2023-07-25 11:40 UTC, leemthompo commented on docs/sync-rules/DROPBOX.md
> +- Content extraction is not supported for paper files with advanced sync rules enabled.
```suggestion
- Content extraction is not supported for Dropbox Paper files when advanced sync rules are enabled.
```

2023-07-25 12:51 UTC, leemthompo submitted a review, later dismissed
LGTM writing wise :)

2023-07-25 12:52 UTC, leemthompo commented on docs/reference/dropbox.md
> +- You can refer to [DROPBOX.md](../connectors/docs/sync-rules/DROPBOX.md) for the correct format to add sync rules. Any errors encountered, will be presented to the user visually in the sync rules ov
```suggestion
- You can refer to [DROPBOX.md](../connectors/docs/sync-rules/DROPBOX.md) for the correct format to add sync rules. Any errors encountered will be reported in the sync rules overview.
```

2023-07-25 13:09 UTC, seanstory approved these changes

2023-07-26 05:44 UTC, leemthompo approved these changes

2023-07-26 10:33 UTC, merged