[8.7] Remove types from "native" which aren't native in this version
elastic/connectors-python pull request #774
Opened 2023-04-14 20:39 UTC by seanstory

Reported by @ppf2 in [this slack thread](https://elastic.slack.com/archives/C01795T48LQ/p1681503868161219?thread_ts=1681155985.696539&cid=C01795T48LQ).

In 8.7, the only native connectors are MongoDB and MySQL. See: https://www.elastic.co/guide/en/enterprise-search/8.7/native-connectors.html

## Checklists

#### Pre-Review Checklist
- [x] this PR has a meaningful title
- [x] this PR links to all relevant github issues that it fixes or partially addresses
- [x] this PR has a thorough description
- [x] Added a label for each target release version (example: `v7.13.2`, `v7.14.0`, `v8.0.0`)

2023-04-17 08:03 UTC, timgrein approved these changes
LGTM

2023-04-17 09:11 UTC, artem-shelkovnikov requested changes
It's not possible to merge this change as our functional test framework depends on connectors that are tested to be in `native_service_types`.

I tried running `NAME=dir make ftest` to run a functional test for our directory connector and it never started, so this change is breaking.

We need to do some follow-ups before we can remove connectors from this list. :(

2023-04-17 13:32 UTC, seanstory commented
> It's not possible to merge this change as our functional test framework depends on connectors that are tested to be in native_service_types.

Thanks for taking a look into this. This seems like poor design on our part. Our functional tests should not rely on the default production YAML file. If I get some free cycles, I'll see if I can decouple them. In the mean time I'll switch this to a draft pr.

2023-04-17 14:59 UTC, wangch079 commented
>This seems like poor design on our part. Our functional tests should not rely on the default production YAML file.

Agree. We should provide a default `config.yml` in [connectors/sources/tests](https://github.com/elastic/connectors-python/tree/main/connectors/sources/tests), and maybe allow each connector to override it.

2023-06-13 19:38 UTC, seanstory commented
supplanted by https://github.com/elastic/connectors-python/pull/1038

2023-06-13 19:38 UTC, closed without merging