[DLS] Rename "permissions sync" to "access control sync"
elastic/connectors-python pull request #970
Opened 2023-05-26 15:27 UTC by timgrein

## Related to https://github.com/elastic/enterprise-search-team/issues/4662

This PR changes the name "permissions sync" to "access control sync"

## Checklists

#### Pre-Review Checklist
- [x] this PR has a meaningful title
- [x] this PR links to all relevant github issues that it fixes or partially addresses
- [x] if there is no GH issue, please create it. Each PR should have a link to an issue
- [x] this PR has a thorough description
- [x] Covered the changes with automated tests
- [x] Tested the changes locally
- [x] Added a label for each target release version (example: `v7.13.2`, `v7.14.0`, `v8.0.0`)

2023-05-26 15:33 UTC, timgrein commented
buildkite test this

2023-05-29 15:35 UTC, tarekziade submitted a review, later dismissed

2023-05-31 10:26 UTC, wangch079 commented on connectors/kibana.py
> +            "last_access_control_sync_scheduled_at": None,
I think, still not correctly sorted

2023-05-31 15:52 UTC, wangch079 approved these changes

2023-06-01 06:26 UTC, wangch079 requested changes
Should also rename `JobType` enum.

2023-06-01 10:24 UTC, timgrein commented
> Should also rename `JobType` enum.

Good catch! Adjusted 👍

2023-06-01 10:32 UTC, wangch079 approved these changes

2023-06-01 13:52 UTC, merged